### ISSUE TITLE
Getting error found below  

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#10]
new_data <- wrapper_fun(file_dir = "H:/Deer/Doe Research/Region 4",  
+  sp_input = "White-tailed Deer", 
+  ageclass_input = "adult", 
+  sex_input = "f", 
+  save_file = "H:/Deer/Doe Research/Region 4/18A.csv") 
Error in eval(expr, envir, enclos) : object 'Animal_ID' not found
>

**Comment by Huh** [comment]
The folder "H:/Deer/Doe Research/Region 4/" can only contain the appropriate files and the column names need to be the same across all the files.  Is that helpful?
Does that file have a column name 18A or does that folder have some other files in it? Josh Nowak 


     On Friday, July 17, 2015 12:33 PM, gfrc11752 <notifications@github.com> wrote:
   

 new_data <- wrapper_fun(file_dir = "H:/Deer/Doe Research/Region 4",    
   -  sp_input = "White-tailed Deer", 
   -  ageclass_input = "adult", 
   -  sex_input = "f", 
   -  save_file = "H:/Deer/Doe Research/Region 4/18A.csv") Error in eval(expr, envir, enclos) : object 'Animal_ID' not found>

**Comment by Huh** [comment]
Sorry, I meant does the file have a column named Animal_ID?  And, is it an encounter history?

What is see in your code above is that you are trying to read and write from the same folder.  This will only work once and then it will fail with an error like above because you have now mixed the original files with the new output.  The best workflow would write the output files to a new directory.
