### ISSUE TITLE
Survival Analysis Question

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#120]
We have an animal that was captured in 2014 and was never heard because the antenna fell out. This individual was then harvested by a hunter in 2015 but we have no monitoring records. How should we handle this situation, censor it altogether because it goes beyond the bounds of known fate recovery? Just so happen a hunter shot it before it died from some other cause.

**Comment by Huh** [comment]
We just had this conversation about deer in Idaho.  The known fate context is not correct for this and it should be a band recovery type model to account for all of the animals that were not heard again and never recovered.  I don't think this information will add much of anything to the analyses except bias.  If this starts happening a lot then perhaps we can think about a band recovery type model, but for the moment I would censor the animal at the last time it was heard.  This is how it is handled in Idaho as well. Josh Nowak 

    On Wednesday, April 20, 2016 12:24 PM, gfrc11752 <notifications@github.com> wrote:
 

 We have an animal that was captured in 2014 and was never heard because the antenna fell out. This individual was then harvested by a hunter in 2015 but we have no monitoring records. How should we handle this situation, censor it altogether because it goes beyond the bounds of known fate recovery? Just so happen a hunter shot it before it died from some other cause. —

**Comment by gfrc11752** [comment]
Censoring was also what I was thinking. Hopefully this doesn’t happen much and it really shouldn’t. Thanks for the clarification!
