### ISSUE TITLE
Survival Calculation Question

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#126]
Is the survival estimate derived using a staggered entry design? For example: 2016, WTD, DAU 11, Adult, Females, I keep getting a survival estimate of ~62%. However, we had 117 marked; of them, 2 censors, 15 deaths, so 100 are currently still alive. I realize September is projected but even if it is a 100% it won't change things a whole lot. 

Another example DAU 11, 2016, WTD , Fawns, 65 collared; of which; 21 died, 9 collars tore off and currently 35 alive. PopR is generating a 44% survival estimate.

I did notice that animals that died from capture myopathy are still not being censored automatically. All capture myopathies should be Dead =True, Censored = True

Examples: 
20161113039   152.043 White-tailed Deer  DAU  11    Mort heard on 3-22-16- capture myopathy

20161113066   152.942 White-tailed Deer  DAU  11    Mort heard on 4-1-16= capture myopathy

Thanks!

**Comment by Huh** [comment]
Yes, we incorporate staggered entry and right censoring in the models.  I will make an opportunity to look at the results shortly.  
Thanks for the detailed report! Josh Nowak 

    On Friday, September 2, 2016 5:39 PM, gfrc11752 <notifications@github.com> wrote:
 

 Is the survival estimate derived using a staggered entry design? For example: 2016, WTD, DAU 11, Adult, Females, I keep getting a survival estimate of ~62%. However, we had 117 marked; of them, 2 censors, 15 deaths, so 100 are currently still alive. I realize September is projected but even if it is a 100% it won't change things a whole lot. Another example DAU 11, 2016, WTD , Fawns, 65 collared; of which; 21 died, 9 collars tore off and currently 35 alive. PopR is generating a 44% survival estimate.I did notice that animals that died from capture myopathy are still not being censored automatically. All capture myopathies should be Dead =True, Censored = TrueExamples: 
20161113039 152.043 White-tailed Deer DAU 11 Mort heard on 3-22-16- capture myopathy20161113066 152.942 White-tailed Deer DAU 11 Mort heard on 4-1-16= capture myopathyThanks!—

**Comment by Huh** [comment]
I looked at this off and on all day.  My thoughts may be a bit disjointed below, but here are some of the thoughts that I had when looking at the model runs.

I really don't see anything suggesting the code is wrong.  I have looked at this from several angles and share some of that below.  Reasons why the estimate is just wrong would be that only a few animals died and so while the marked sample is large the sample that actually gives us information is not.  I could imagine that if I played with this model the prior may have some influence given the number that died.  I can try a model run with an informative prior to see what happens and test that theory.  @paul-lukacs might have something to add, not sure...

I would suggest that the 0.78 in November is pretty influential to the estimate.  Every other month is 0.98 or higher.  If you were to remove that November estimate the product of the remaining months is 0.93.  I would guess a bunch of does in that DAU were harvested.  In general, when I get ungulate data on a unit that has unrestricted harvest (male or female) survival drops to something between 0.4 and 0.6.  Given that 0.78 in November I think it is conceivable that survival is that low, but I am not saying it is true.  I did a quick run, but did notice the upper CI of survival is around 0.8.  I also ran the known-fate model and it agrees with the multi-state estimate.

Looking at other sources of data the average adult doe is pregnant and has 1.86 fawns.  The ratio in the fall is just above 1, which gives us about a fawn per doe at the end of the year.  So, ignoring juveniles we only need about 0.5 of the does to survive to achieve a stable population, using back of the napkin biology.  The point is, I don't find that number to be completely unreasonable.

The other thing to note is that there are only a handful of deaths.  It would be better if a few more had died.  We are also estimating 2 months because there is very little information in August and September has none.  The CI's reflect this observation.

I am currently working on another way to conceptualize the survival models that may help with the observation of too few deaths in any given year.  I know that doesn't help right now, but you should know that I am still working for you to make these estimates as good as they can be.

**Comment by paul-lukacs** [comment]
I took a look at the data and it appears the most recent collar checks popping up are from 8/2/16.  Therefore, both August and September have no data.

The November estimate came with fewer collars and a large number of mortalities.

Paul

On Sep 6, 2016, at 4:50 PM, Josh Nowak <notifications@github.com<mailto:notifications@github.com>> wrote:


I looked at this off and on all day. My thoughts may be a bit disjointed below, but here are some of the thoughts that I had when looking at the model runs.

I really don't see anything suggesting the code is wrong. I have looked at this from several angles and share some of that below. Reasons why the estimate is just wrong would be that only a few animals died and so while the marked sample is large the sample that actually gives us information is not. I could imagine that if I played with this model the prior may have some influence given the number that died. I can try a model run with an informative prior to see what happens and test that theory. @paul-lukacs<https://github.com/paul-lukacs> might have something to add, not sure...

I would suggest that the 0.78 in November is pretty influential to the estimate. Every other month is 0.98 or higher. If you were to remove that November estimate the product of the remaining months is 0.93. I would guess a bunch of does in that DAU were harvested. In general, when I get ungulate data on a unit that has unrestricted harvest (male or female) survival drops to something between 0.4 and 0.6. Given that 0.78 in November I think it is conceivable that survival is that low, but I am not saying it is true. I did a quick run, but did notice the upper CI of survival is around 0.8. I also ran the known-fate model and it agrees with the multi-state estimate.

Looking at other sources of data the average adult doe is pregnant and has 1.86 fawns. The ratio in the fall is just above 1, which gives us about a fawn per doe at the end of the year. So, ignoring juveniles we only need about 0.5 of the does to survive to achieve a stable population, using back of the napkin biology. The point is, I don't find that number to be completely unreasonable.

The other thing to note is that there are only a handful of deaths. It would be better if a few more had died. We are also estimating 2 months because there is very little information in August and September has none. The CI's reflect this observation.

I am currently working on another way to conceptualize the survival models that may help with the observation of too few deaths in any given year. I know that doesn't help right now, but you should know that I am still working for you to make these estimates as good as they can be.

�
