### ISSUE TITLE
BIT questions about GF104 database that generates API data

### ISSUE THREAD

**Issue by 12382** [Huh/PopR_SDGFP#210]
BIT is asking a question that I need a bit of clarification.  They are unsure how the Capture_Unit, Monitoring_Unit, and Fate_Unit are supposed to be filled in on our end for the survival files from the Collars Database.  Most of the entries have an NA in these columns, but some capture events have a unit specified in the Capture_Unit, and 22 moralities have a Fate_Unit assigned.  Is this something we need to be filling in?  Or is it a relic of historic data that didn't have a capture location?  I feel this would be a lot of work for BIT to maintain current and past Firearm Hunting Unit shapefiles, if this is something that PopR is already doing based on capture location data.  Let me know how you need them to proceed to complete this API update.  They hope to get the rest of 2017 and all of 2018 into this database soon.  Feel free to call if you need further clarification.

**Comment by Huh** [comment]
Most of this is a relic.  

I use capture unit when it is available, but don't need it if lat and lon are supplied.  It is really important that we know where an animal was captured or we can't assign the survival estimate to a place.

Monitoring unit would be nice, but is not necessary for anything on my end.  The one time it helps is when we need to know where an animal was last heard.  Again, if the lat and lon are provided this is not an issue.

I am not using the mortality unit.  The lat and lon are sufficient here and used to show users where animals died.  We do want lat and lon for this type of record though because someday someone will ask about movment or how many animals from unit x were killed in unit y and that sort of thing.

For your reference all lat/lon data are referenced to a 2014 shapefile to assign unit.  The assignment works hierarchically such that if lat/lon are present we extract all information from that, but if they are missing we rely on unit to assign spatial information and so up the ladder.  I like the idea of redundancy and it would be nice if we retained the capture unit data, if possible and not too much work, so that when lat/lon are missing or bad the data are still useful.  In the absence of location information we will be forced to throw animals out of the analysis. 

Josh
