### ISSUE TITLE
Constant Only Option for Survival Structure

### ISSUE THREAD

**Issue by nort0160** [Huh/PopR_SDGFP#214]
Hey Josh,

I am trying to get some preliminary annual deer survival estimates, and the structure tab is only allowing me to select constant space and time. The test I was running was for DAU 9, WTD 2016-2018. The output looks to be estimating a single monthly survival estimate across all 3 years. I believe for now we want to estimate ~separate monthly estimates each year (i.e., 36 estimates for the 3 yrs), which are smoothed with some sort of temporal smoothing you have structured in the model? Another question I would have down the road is how the spatial and temporal smoothing works (autoregressive or evenly shared across space and time)?

Anyway, wondering if it is just a glitch regarding how I subset the data or something I am overlooking on my end?

Eventually, I plan to run the known fates model once for muleys and once for wtd for 2018, assuming I would select separate sex, age, space, and time. I am sure some of the simpler questions I have will get cleared up once I run through a training with you guys, but in the meantime, just wanted to get some preliminary results for our bios here. I assume the multi-state option is for cause-specific mortality esitmates?

Thanks,

Andrew

**Comment by Huh** [comment]
Hey Andrew,

The time varying option is not available until you are using 5 years of
data.  This is to prevent trying to estimate random effects with tiny
sample sizes.

The spatial models use ordinary random effects.  If you want to use this
option the don't subset spatially.

The multi-state models are required for the IPM as it uses the harvest
mortality in the population reconstruction.

Josh

**Comment by nort0160** [comment]
Thanks Josh. Just to clarify, if I just wanted to estimate survival for 2018, there is no way to model separate monthly estimates? However, if I wanted to model monthly estimates, I would just need to make sure the data are selected form 2013 to 2018, and if there are no data for 5 consecutive years, I can only model survival constant among months?

I am also getting kicked off the server about 50% of the time I try to load data or run models. Not sure if that is a BIT issue or MT?

Andrew

**Comment by lindbloom** [comment]
I am getting disconnected from server 100% of the time.

**Comment by Huh** [comment]
I will look through the logs for errors and see if I can do something about
the disconnecting.

**Comment by Huh** [comment]
For the time varying random effects and monthly survival estimates...

The models setup the global distribution over all *Marches, Aprils, etc* and then if sufficient information exists in a particular March it can earn the right to be different (marginal effect).  That said, we limit the use of time-varying estimation to data that has at least 5 years so that the sample size to estimate the variance of the random effect is at least 5.  We could setup the models to treat each month as a random effect, but then we smooth the effect of March, April too much.  The mean of survival is relatively flat and consistent for most months, but late spring is a time of death.  We want the maximum flexibility in late spring so we don't smooth low data months with lots of death back to the overall mean, but instead if smoothing occurs it goes back to the mean for the month.  In addition, fitting a survival model for one year at a time creates numerous issues when missing data exist and it reduces the sample size considerably.  The time and space varying models are attempting to share as much information as possible to provide precise and accurate estimates.  In this context we prefer to estimate the models for all years and potentially space even if the desired estimate is June of 2018.  The month by year structure is available in the output of the larger models.

Does that make sense?  Hope I explained half way decent.  Feel free to call if you want to discuss more.

**Comment by Huh** [comment]
This issue is fixed for all cases where there is > 1 year of data available, per phone call with Paul and SD.
