### ISSUE TITLE
Duplicate Encounter Histories

### ISSUE THREAD

**Issue by nort0160** [Huh/PopR_SDGFP#216]
Sorry for the additional harassment today, but I was going through the encounter histories for all the juvenile and adult deer, and found 31 IDs (listed below) that appear to have some duplicated encounter histories (e.g., 2017312018) or 2 different encounter histories for the same animal (e.g., 2014521007 and 2016321020) 

Lauren scanned through the capture, monitoring, and fate records and didn't seem to find where the error could have occurred in the collars database. For example, 2014521007 was captured as a neonate, and the collar tore off, but when the encounter history is created it appears to additionally link to the monitoring information for some adult with a lost signal starting in Sept 2014, when it was still a juvenile.

Thanks for looking into all of this!

2009613005
2014511003
2014511005
2014521007
2014521011
2014521012
2014611002
2014713036
2015111004
2015311045
2015421005
2015611016
2015611045
2015611047
2015611048
2016311005
2016311024
2016321001
2016321020
2016321021
2016321024
2016321040
2016322028
2016323052
2016323073
2016623004
2016623017
2017312002
2017312018
2017313032
2017322036

**Comment by Huh** [comment]
The first animal `2009613005` has multiple mortality records.  The first mortality record is on  05/01/2015 and the status is 1, which can't be true.  A status of 1 is alive, 2 is harvested and 3 is other mortality cause.  Because the code picks up the first mortality record and uses that one the encounter history for this animal extends only until 05/01/2015 and the status is 1 when it exits the model.  The second mortality record has status 3, but occurs on 08/20/2015.  This is likely the correct record.  I don't think it would be good for PopR to ignore the multiple mortality records.  I think the appropriate behavior is to remove animals with multiple mortality or capture records and report this to the user.  I will implement this feature unless I hear otherwise.

**Comment by Huh** [comment]
`2016321040` is similar in that it has multiple mortality records
`2015611048` has multiple mortality records
`2014611002` has multiple mortality records

It is worth noting that these duplicate records are not truly duplicates and so difficult to deal with.  If a join is done in the DB or otherwise both records will be retained because some of the information is different.  For example,
```R
PopR

ID1	Date1	Species	Sex	Age	Frequency	Status	Fate	Censored	Dead	CollectionType
2014611002	6/28/2015 12:00:00 AM	White-tailed Deer	m		151.262	1	other	T	F	Deer Mortality
2014611002	7/24/2015 12:00:00 AM	White-tailed Deer			151.262	1	Collar Tore Off	T	F	Deer Mortality
```

**Comment by Huh** [comment]
This seems to be resolved and we have new tools to monitor these types of errors.  Reopen if you disagree or want to continue this conversation
