### ISSUE TITLE
No option to select monthly survival

### ISSUE THREAD

**Issue by nort0160** [Huh/PopR_SDGFP#220]
Most of the time the data will load, but about 1 in 5 attempts, I get the same error message Andy described earlier this morning. Also, I am unable to select monthly intervals when I choose the juvenile option (both white-tails and muleys don't allow). It looks as though there are 5 years of juvenile data, and I did not adjust the toggle for year (i.e., using all possible years).

Thanks!

**Comment by nort0160** [comment]
Also WTD, all DAU, Male, Adult, 2007-2018, Multi-State, WSI, None (censor), Same (sex), Constant (time [only option]). DAU (space) returns "Survival modeling error."

**Comment by Huh** [comment]
The error about please contact the system administrator or whatever?  But
nothing crashes?  And if you hit the dismiss button does the data show up?

There are only 4 years of juvenile data, so the option is not available.
The slider may say "try to pick up all data" between 2007 and 2018, but the
chart to the right shows data only exists from 2014 to 2018.  Do you see
more data somewhere else?

As to the male WTD model, I see a problem(?) and will take a look.  I need
to get on the road right now though.  That said, given the low male sample
sizes why not use male and female at the same time and model the difference
between the two?

Thanks,

Josh

**Comment by lindbloom** [comment]
I'm either confused or concerned about the "4 years" restriction listed above.  If we have 3 years of juvenile data with 100+ animals and year 3 we have a severe deer killing winter, we obviously want to use those data in our modeling exercises.  Is this not an option?

**Comment by Huh** [comment]
The data are in there.  The rule is more about estimating a unique estimate
in each year.  The sample size is 3 in your example because there are 3
years.  This is the concern.  I can remove it if you like.

I am doing training in Idaho today, but if you want to chat with Paul about
it he may be available.

@paul-lukacs




[image: speedgoat logo] <http://www.speedgoat.io/>
*Josh Nowak*, President
*Speedgoat Wildlife Solutions*
(406) 214-7666

   - [image: Check out my work on Github!] <https://github.com/Huh>
   - [image: Connect with me on LinkedIn!]
   <https://www.linkedin.com/in/josh-nowak-speedgoat/>

**Comment by paul-lukacs** [comment]
I’m available if you want to discuss.

I’m not sure I understand the question.  The limit on numbers of years refers to fitting random effects because years become the sample size for year to year standard deviation.  If you are concerned about a specific year, you can subset to that year and fit a model to just those data.

**Comment by nort0160** [comment]
Thanks Paul. Andy sent me some of the IPM documentation you guys have put together, and I was wondering if you had some similar documents regarding the survival models? If convenient, it would be nice to chat with you guys to get a better idea of how the survival models are structured, and eventually the IPM. I am thinking if I go through some of the survival model descriptions beforehand, it might help with my understanding and save you guys some time. Otherwise, I am happy to chat first, and then go through some of the model structure afterward? Whatever is easiest for you all, just let me know. My schedule is mostly open this month.

Thanks.

**Comment by Huh** [comment]
I updated the survival models in this repository in hopes that they will
help your conversation.

https://github.com/Huh/PopR_SDGFP > Models > Surv

I also updated the IPM models in case they are of interest to you.

I am working on better documentation for the workflow and data handling.
You can expect something soon, which I will post on the documents site
accessible through speedgoat.io or spdgt.com under the login link in the
top right.

**Comment by Huh** [comment]
I believe this is resolved and am closing for the sake of house keeping.  If there are unresolved issues or enhancements please re-open or open a new issue to reflect that.
