### ISSUE TITLE
Herd comp data zeros

### ISSUE THREAD

**Issue by lindbloom** [Huh/PopR_SDGFP#223]
Trying to figure out why there are zeros in the count and effort data tables for wtd and md in 2018, and several previous years.   

On a related note, could we have "groups counted" added to the output table?  Always nice to have that right next to the ratios as some DAUs will have low counts (e.g., mule deer east river) and therefore necessary to keep this upfront with the estimate.  Also, this would be helpful for evaluating sample size goals.

**Comment by Huh** [comment]
I don't see any 0's.  I was using 
- Last Download 12-07-2018
- Mule Deer
- DAU 1 and All
- Year All and just 2018
- Multiple structures

Can you give me an idea of the model structure and data subsetting you used to get this result?

**Comment by Huh** [comment]
Nevermind, I see what you were saying.  I was looking in the wrong place.

**Comment by Huh** [comment]
This was because NA or blanks were present in the data coming from the API.  We now calculate the summary statistics by ignoring the NA values and the tables produce counts for each year by x combination.

On a related note, I have a rather strong opinion that when collecting count data an NA means  something was not entered, not measured or otherwise unavailable.  If the count is 0 then a 0 should be entered.

**Comment by Huh** [comment]
I have now added the number of groups counted and the number of individuals counted to the output table.

I am closing because I believe this to be resolved
