### ISSUE TITLE
Herd Composition

### ISSUE THREAD

**Issue by lindbloom** [Huh/PopR_SDGFP#234]
We have found some substantial differences in the data being read by PopR and the data that have produced some of our historical herd comp estimates.  After further review, it appears this is all fixable on our end by fixing the raw data for PopR to read, which we are able to do and have done from 2016-18.  With 2015 and years prior, however, we don't have a good way to go back and fix the raw data.  It seems that many of the summary data tables were manipulated by hand to reflect the best data interpretation at the time, but the actual raw data was not changed.  Some of this may have been due to some folks still using paper, but regardless we can't fix it.  

Andrew and I discussed this at length this afternoon and here's what we propose.  For 2016 and moving forward, we use PopR to estimate herd comp and update the IPM.  For everything before and including 2015, we provide you with a summary table of counts, or estimates, and PopR just uses these as is.   Does that seem like the best solution and if so, what format would work best.

**Comment by gfrc11752** [comment]
I’m very curious as to what the discrepancies were? “It seems that many of the summary data tables were manipulated by hand to reflect the best data interpretation at the time, but the actual raw data was not changed”, what are you referencing here?

**Comment by Huh** [comment]
This solution works for me as long as the numbers are reasonable.  

I think it would be best if you just provided estimates.  I will email the estimates that Kevin put together in the required format.  If you could approve this data or change it and send it back that would be great. 
 I will also change the IPM database and change the year selection for composition to 2016-Present so folks don't change anything.

Sound good?

**Comment by nort0160** [comment]
[compare_smry.xlsx](https://github.com/Huh/PopR_SDGFP/files/2792810/compare_smry.xlsx)

Attached is a quick and dirty summary comparing what we had in historic summary tables by DAU versus what PopR produces based on the lat/long of observations. From 2016 and moving forward, most of the differences can be fixed because they are the results of observations entered back at the office, which records lat/long in a different DAU (enter at Rapid City Office in DAU 3 when observation occurred in DAU 2). 

We are working on correcting the raw data lat/long using GIS for 2016, 2017, and 2018. Moving forward we hope to have columns in PopR input and raw data to indicate disagreement between lat/long DAU versus user-input DAU (see 3 bullet points at the end of issue #229 ).

**Comment by Huh** [comment]
You now have full control over ipm databases.  With the new tools under the IPM tab you can:

- Create new database
- Create new databases using old data stored in a csv as a starting point (e.g. ratios)
- Delete entire databases
- Edit databases, which means you can delete rows if, for example you fit a survival model and included 2019 today

Within each of the other tabs you can choose, which database to update or just roll through all of them and update all the databases

I am calling this closed unless other comments remain unanswered
