### ISSUE TITLE
Sex info for two animals

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#24]
Animals 

2015221027
2015321006

have no sex information entered, could you find that and reply please.

**Comment by gfrc11752** [comment]
Sex was not determined at capture for 2015221027; therefore, that one will have to remain NA. 2015321006 slipped through my cracks and should not be on the list because that collar was never deployed. Interns selecting the wrong frequency in a pick list will generate a new ID number. Please remove 2015321006 from your master file. Thanks!
