### ISSUE TITLE
Composition Data Error

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#29]
The following rows are shifted one column to the right.
```R
       ID Year       Date Region Unit Species          Latitude Longitude  YOY_Count Female_Count Male_Count Total_Count Method  Observer
162 31737 2013 10/31/2013      2  30A       B         Mule Deer  43.26089  -99.26745            0          1           0      1  Daylight
214 31788 2013 10/30/2013      2  50A       B White-tailed Deer  44.38605 -100.39543            0          1           1      2  Daylight
373 31946 2013 10/25/2013      2  58A       D White-tailed Deer  44.47955 -100.61464            3          3           0      6  Daylight
753 32325 2013 10/16/2013      2  58A       D White-tailed Deer  44.43989 -100.40403            2          4           1      7 Spotlight
755 32326 2013 10/16/2013      2  58A       D White-tailed Deer  44.44583 -100.40112            0          1           1      2 Spotlight
```

**Comment by Huh** [comment]
Viewing this stuff on the github website is easier because I formatted the data for it....FWIW.

**Comment by Huh** [comment]
Should Heather join GitHub?

**Comment by gfrc11752** [comment]
Yes…..

**Comment by gfrc11752** [comment]
Heather,

Can you please fix units 30AB, 50AB and 58AD in the fall classification table. It appears they are off a column most likely due to how the data was converted from text to column in excel?



ID Year       Date Region Unit Species          Latitude Longitude  YOY_Count Female_Count Male_Count Total_Count Method  Observer
162 31737 2013 10/31/2013      2  30A       B         Mule Deer  43.26089  -99.26745            0          1           0      1  Daylight
214 31788 2013 10/30/2013      2  50A       B White-tailed Deer  44.38605 -100.39543            0          1           1      2  Daylight
373 31946 2013 10/25/2013      2  58A       D White-tailed Deer  44.47955 -100.61464            3          3           0      6  Daylight
753 32325 2013 10/16/2013      2  58A       D White-tailed Deer  44.43989 -100.40403            2          4           1      7 Spotlight
755 32326 2013 10/16/2013      2  58A       D White-tailed Deer  44.44583 -100.40112            0

Thanks!

Kevin

**Comment by Huh** [comment]
If she joins have her send me her ID and I will add her as a collaborator.

**Comment by HeatherMcW** [comment]
I removed the commas for 30A,B, 50A,B, and 58A,D. This format appears in the three harvest tables, should I remove the commas there as well?

**Comment by gfrc11752** [comment]
Yes, make them consistent across all tables.

Thanks!

**Comment by HeatherMcW** [comment]
Units have been updated.

**Comment by Huh** [comment]
Ok, so we just removed commas from the Composition and Harvest data.  If we are going to do that we should remove them from all data sources, pregnancy, survival, etc.
Is that what was done?  I need to retool some things to accommodate this change.  It is not a problem. Josh Nowak 


     On Wednesday, August 26, 2015 8:51 AM, HeatherMcW <notifications@github.com> wrote:
   

 Units have been updated.—

**Comment by HeatherMcW** [comment]
I removed commas in the Harvest, Unit, UnitInfo, Survival.Individual, Tag, and License tables.

I did not see units 30A,B, 50A,B, or 58A,D in the Pregnancy table.

**Comment by Huh** [comment]
Thank you Heather.  I will keep an eye out for commas. Josh Nowak 


     On Wednesday, August 26, 2015 12:02 PM, HeatherMcW <notifications@github.com> wrote:
   

 I removed commas in the Harvest, Unit, UnitInfo, Survival.Individual, Tag, and License tables.I did not see units 30A,B, 50A,B, or 58A,D in the Pregnancy table.—
