### ISSUE TITLE
Tags Data in Database has duplicates

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#50]
True duplicates = 83 rows are duplicates of some other row:

```R
> filter(tgs, Year == 2014, Unit == "03A", UserGroup == "Refuge")
  Year Unit TagType UserGroup TotLicSold
1 2014  03A       1    Refuge         22
2 2014  03A       3    Refuge         11
3 2014  03A       1    Refuge         22
4 2014  03A       3    Refuge         11
5 2014  03A       1    Refuge         23
6 2014  03A       3    Refuge         11
7 2014  03A       1    Refuge         22
8 2014  03A       3    Refuge         11
```

There are also 225 entries that duplicate year, unit, tagtype and usergroup, but provide conflicting information about the total number of licenses sold.  An example is shown below:

```R
91 2014  03A       1    Refuge         22
92 2014  03A       3    Refuge         11
93 2014  03A       1    Refuge         23
```

Am I missing another column that would separate these values or is this just an error?

FYI, I am using total number of licenses sold so I can continue working on developing the tools until total licenses available is available to me.

**Comment by HeatherMcW** [comment]
it looks like you converted the unit field value for the Refuge user group to the county if falls within. Each of the three refuges has the same unit boundary but multiple seasons within a year that are open for different days. 

For example: Sand Lake Refuge 2014
RFD-SL1 tags available from Nov 8-12; Dec 27-Jan 4
tag 01 - any deer
tag 03 - any antlerless
RFD-SL2 tags available from  Nov 13-17; Dec 27-Jan 4
tag 01 - any deer
tag 03 - any antlerless
RFD-SL3 tags available from Nov 18-23; Dec 27-Jan 4
tag 01 - any deer
tag 03 - any antlerless
RDF-SL5 tags available from Dec 1-7; Dec 27-Jan 4
tag 01 - any deer
tag 03 - any antlerless

Kevin and I discussed a work around for this so to sum the 4 seasons dates based on tag type so that you would now have

Year      Unit    TagType    UserGroup    TotLicSold
2014      SL       01            Refuge         89
2014      SL       03            Refuge         44

**Comment by HeatherMcW** [comment]
Josh,

If you feel this solution will fix the duplicate errors I can get started on this today. I would also update the harvest table to match the new grouping for the Tag table.

**Comment by HeatherMcW** [comment]
i have entered tags available for the three firearms seasons for 2014-2011. I should be able to get the rest of the years entered tomorrow.

**Comment by Huh** [comment]
The unit boundary issue relates back to when I asked about how I was aggregating the units to the 2014 reference.  I recall some emails and passing along a table if you want to check it out again.  

The SLC, Refuge and maybe one other Unit designation were changed to the larger unit in which they fell in 2014.  

If I understand correctly, the suggestion is that I sum the Refuge tags within Year, Unit, TagType to aggregate the duplicates into a single value.  Is this correct?

**Comment by HeatherMcW** [comment]
yes. Do you need me to modify anything on my end to make this easier for your analysis?

**Comment by Huh** [comment]
No thank you, I will handle it on my end. Josh Nowak 


     On Friday, September 11, 2015 12:07 PM, HeatherMcW <notifications@github.com> wrote:
   

 yes. Do you need me to modify anything on my end to make this easier for your analysis?—
