### ISSUE TITLE
Survival Encounter History

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#64]
Heather,

Currently I cannot retrieve the survival encounter history file. Can you please go in and verify all of the data is in the sequel database and everything is working on our end?

Thanks!

**Comment by Huh** [comment]
I think somebody has two entries for sex.  The data comes my way just fine, but when it tries to assign a single sex to each individual it fails.  

This raises a good point, the data check should download the data independent of the setup tab, which will take longer, but allow troubleshooting.

The issue is likely that...
2015111002 was recorded as male and female

```R
> filter(survd, ID1 == 2015111002) %>% select(ID1, Sex)
          ID1 Sex
1  2015111002   m
2  2015111002   f
3  2015111002   f
4  2015111002   f
5  2015111002   f
6  2015111002   f
7  2015111002   f
8  2015111002   f
9  2015111002   f
10 2015111002   f
11 2015111002   f
12 2015111002   f
```

**Comment by Huh** [comment]
I verified that fixing that entry will fix the issue.

**Comment by gfrc11752** [comment]
Alright, we will have to get that entry changed in the sequel database ASAP.

**Comment by gfrc11752** [comment]
How is the IPM coming along??

**Comment by Huh** [comment]
You will have something no later than Monday

**Comment by gfrc11752** [comment]
Sounds great!!

**Comment by gfrc11752** [comment]
I’m excited!
